name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: [self-hosted, Linux, X64]

    steps:

    - name: Test Runner
      run: |
        hostname
        whoami
        php -v

    - name: configure git safe directory
      run: |
        git config --global --add safe.directory /var/www/.uat/apps/monapp

    - name: Deploy Laravel
      run: |
        cd /var/www/.uat/apps/monapp
        git fetch origin main
        git reset --hard origin/main
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan optimize:clear
        php artisan optimize
        sudo systemctl reload apache2

    - name: Notification email
      if: always()
       uses: dawidd6/action-send-mail@v3
       with:
         server_address: msg.acsi.cg
    server_port: 587
    username: dmoukilou@acsi.cg
    password: pcx3knj
    subject: "CI/CD Laravel - Résultat du déploiement"
    to: votre.email@acsi.cg
    from: github-actions@acsi.cg
    body: |
      Statut : ${{ job.status }}

      Application : monapp
      Commit : ${{ github.sha }}
