name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: [self-hosted, Linux, X64]

    steps:

    - name: Test Runner
      run: |
        hostname
        whoami
        php -v

    - name: Deploy Laravel
      run: |
        cd /var/www/.uat/monapp
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan optimize:clear
        php artisan optimize
        sudo systemctl reload apache2